import type { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";

export const TERRAIN_LAYERS: LayerSpecification[] = [
  {
    id: "hillshade",
    type: "hillshade",
    source: "dem",
    maxzoom: 14,
    layout: {
      visibility: "visible",
    },
    paint: {
      "hillshade-exaggeration": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        5,
        0.35,
        10,
        0.125,
        14,
        0,
      ],
      "hillshade-shadow-color": [
        "interpolate",
        ["linear"],
        ["zoom"],
        6,
        "rgba(0,0,0,0.25)",
        8,
        "rgba(0,0,0,0.075)",
        13,
        "rgba(123, 123, 123, 0)",
      ],
      "hillshade-highlight-color": [
        "interpolate",
        ["linear"],
        ["zoom"],
        6,
        "#F5E1A490",
        8,
        "#F5E1A450",
        13,
        "#F5E1A410",
      ],
    },
  },
  {
    id: "contours",
    type: "line",
    source: "contours",
    "source-layer": "contours",
    minzoom: 9,
    layout: {
      visibility: "visible",
      "line-join": "round",
      "line-cap": "round",
    },
    paint: {
      "line-color": [
        "match",
        ["get", "level"],
        1,
        "#9d8b7a",
        0,
        "#b3a89d",
        "#9d8b7a",
      ],
      "line-opacity": [
        "interpolate",
        ["linear"],
        ["zoom"],
        9,
        0,
        12,
        0.5,
        16,
        0.7,
      ],
      "line-width": [
        "interpolate",
        ["linear"],
        ["zoom"],
        9,
        ["match", ["get", "level"], 1, 0.35, 0.25],
        12,
        ["match", ["get", "level"], 1, 0.4, 0.3],
      ],
    },
  },
  {
    id: "contours-label",
    type: "symbol",
    source: "contours",
    "source-layer": "contours",
    minzoom: 15,
    filter: [">", ["get", "level"], 0],
    layout: {
      "symbol-placement": "line",
      "text-size": 10,
      "symbol-spacing": 1000,
      "text-field": ["concat", ["number-format", ["get", "ele"], {}], "m"],
      "text-font": ["Noto Sans Regular"],
      visibility: "visible",
    },
    paint: {
      "text-color": "#9d8b7a",
      "text-halo-color": "#e1e1e1",
      "text-halo-width": 1.5,
      "text-halo-blur": 2,
      "text-opacity": ["interpolate", ["linear"], ["zoom"], 15, 0, 15.5, 1],
    },
  },
];
